[project]
name = "quant-predictive-analysis"
version = "0.1.0"
description = "Produce analysis on stocks in a scalable way"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.3",
    "pandas>=2.3.3",
    "yfinance>=1.0",
]
